### ISSUE TITLE
3.1.7版登录登出及获取用户信息的问题

### ISSUE THREAD

**Issue by allentan3** [dotnetcore/osharp#198]
### 描述一下BUG
在Issue#194中，我有描述3.1.7版的一个Bug，指出在调用/api/Identity/Token登录后，再调用/api/Identity/Profile时会返回204错误，后来开发者指出可以在基类上添加以下属性：
[Authorize(Policy = FunctionRequirement.OsharpPolicy, AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
这确实可以解决上面的204错误问题，但是现在会出现一个新的问题，在登录后再调用/api/identity/logout登出系统时，会直接报一个异常，相关异常信息如下：
System.InvalidOperationException: No sign-out authentication handler is registered for the scheme 'Identity.External'. The registered sign-out schemes are: Identity.Application. Did you forget to call AddAuthentication().AddCookies("Identity.External",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignOutAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Identity.SignInManager`1.SignOutAsync()
   at Liuliu.Demo.Identity.IdentityService.Logout(Int32 userId) in E:\Projects\OSharp-master3.1.7\OSharp-master\samples\web\Liuliu.Demo.Core\Identity\IdentityService.cs:line 274
   at Liuliu.Demo.Web.Controllers.IdentityController.Logout() in E:\Projects\OSharp-master3.1.7\OSharp-master\samples\web\Liuliu.Demo.Web\Controllers\IdentityController.cs:line 417
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OSharp.AspNetCore.JsonExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in E:\Projects\OSharp-master3.1.7\OSharp-master\src\OSharp.AspNetCore\JsonExceptionHandlerMiddleware.cs:line 49
   at OSharp.AspNetCore.JsonExceptionHandlerMiddleware.InvokeAsync(HttpContext context) in E:\Projects\OSharp-master3.1.7\OSharp-master\src\OSharp.AspNetCore\JsonExceptionHandlerMiddleware.cs:line 66
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

在去除AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme这个属性后，这个登出方法可以正常使用，但是/api/Identity/Profile方法返回204的问题就无法解决。

### 期望行为
修复以上Bug

### 附加上下文，如截图
![image](https://user-images.githubusercontent.com/13568807/103988259-bf510880-51c8-11eb-9a0a-76ac170570d1.png)

**Comment by gmf520** [comment]
已修复
