### ISSUE TITLE
mysql无法数据迁移，同样的配置sqlserver可以正常运行

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#82]
PM> Add-Migration InitialCreate
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
PM> add-migration AddBlogsEntities
entryAssemblyName: yhy.demo.Web
To undo this action, use Remove-Migration.
PM> update-database
entryAssemblyName: yhy.demo.Web
Applying migration '20190514084927_AddBlogsEntities'.
Done.
PM> update-database
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.

**Comment by gmf520** [comment]
https://github.com/i66soft/osharp/issues/30#issuecomment-492497556
可以看看这个步骤

**Comment by 240011814** [comment]
那个我看过了
在Web项目下Startups文件夹下，排除SqlServer 的 SqlServerDefaultDbContextMigrationPack.cs, SqlServerDesignTimeDefaultDbContextFactory 两个文件，添加MySqlDefaultDbContextMigrationPack.cs, MySqlDesignTimeDefaultDbContextFactory文件
这两个文件重命名提示已经存在

**Comment by gmf520** [comment]
文件已经有了的，你显示所有文件，添加进工程即可
